language: php

php:
  - 7.4

services:
  - mysql

install:
  - mysql -e 'CREATE DATABASE test_route_usage;'

before_script:
  - travis_retry composer update --no-interaction --no-suggest --prefer-source

script:
  - vendor/bin/phpunit
